# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Arcsii < Formula
  desc "Beautiful terminal-based code architecture visualizer with ASCII art"
  homepage "https://github.com/barisercan/arcsii"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/barisercan/arcsii/releases/download/v0.1.0/arcsii_0.1.0_darwin_amd64.tar.gz"
      sha256 "201b3bd21da95285b43df3b0ce48d80fff046dbf2c093e5707e21435253a4c5e"

      def install
        bin.install "arcsii"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/barisercan/arcsii/releases/download/v0.1.0/arcsii_0.1.0_darwin_arm64.tar.gz"
      sha256 "ffe018cec67f63c72051f37cdbcd8de78e1b35c5c738efb4c3a04f98ba94896a"

      def install
        bin.install "arcsii"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/barisercan/arcsii/releases/download/v0.1.0/arcsii_0.1.0_linux_amd64.tar.gz"
      sha256 "cd012f5ba22b3872fb9db63b77834c56aa493cb246fe7f09e646cffc1a62db92"
      def install
        bin.install "arcsii"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/barisercan/arcsii/releases/download/v0.1.0/arcsii_0.1.0_linux_arm64.tar.gz"
      sha256 "eb590f15250fb0f0115a5017c55f1572162f5ee51d7c0cb81116d77e57bd8c47"
      def install
        bin.install "arcsii"
      end
    end
  end

  test do
    system "#{bin}/arcsii", "--version"
  end
end
