# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Arcsii < Formula
  desc "Beautiful terminal-based code architecture visualizer with ASCII art"
  homepage "https://github.com/barisercan/arcsii"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/barisercan/arcsii/releases/download/v0.2.0/arcsii_0.2.0_darwin_amd64.tar.gz"
      sha256 "df004b677e9a67bf7746782665eaedf09f9f81f49a6c78fe2d55eb2448e7cca0"

      def install
        bin.install "arcsii"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/barisercan/arcsii/releases/download/v0.2.0/arcsii_0.2.0_darwin_arm64.tar.gz"
      sha256 "4a066491536a3df82ba4ec340f099a4dd09541e4d74bea76ed098e8e2c92c919"

      def install
        bin.install "arcsii"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/barisercan/arcsii/releases/download/v0.2.0/arcsii_0.2.0_linux_amd64.tar.gz"
      sha256 "dfe34385afba0984759ebe2224743cf49902f9949b490a90183414ba8b97af87"
      def install
        bin.install "arcsii"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/barisercan/arcsii/releases/download/v0.2.0/arcsii_0.2.0_linux_arm64.tar.gz"
      sha256 "c374e9b7906c019053d89d3541accfdb7ebe0dc405e9294bd1d6413bed5a398f"
      def install
        bin.install "arcsii"
      end
    end
  end

  test do
    system "#{bin}/arcsii", "--version"
  end
end
